import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// 1. IMPORTA EL PROVIDER
import { PropiedadesProvider } from "../context/PropiedadesContext"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* 2. ENVUELVE EL CONTENIDO CON EL PROVIDER */}
      <body className="min-h-full flex flex-col">
        <PropiedadesProvider>
          {children}
        </PropiedadesProvider>
      </body>
    </html>
  );
}